substitutions:
  device_name: aircocontroller
  device_ip: 10.119.2.20

esphome:
  name: ${device_name}
  friendly_name: ${device_name}

esp8266:
  board: d1_mini

external_components:
  - source: github://dmagyar/esphome_gree_hvac
    components: [ greeuart ]
    refresh: 0s

uart:
  id: ac_uart
  tx_pin: 1
  rx_pin: 3
  baud_rate: 4800
  data_bits: 8
  parity: EVEN
  stop_bits: 1

climate:
  - platform: greeuart
    name: None
    # None only if you set "friendly_name" in substitutions
    # name: "Kitchen AC"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: ${device_ip}
    gateway: 10.119.2.1
    subnet: 255.255.255.0
    dns1: 10.119.0.1
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "ESPHOME"
    password: "12345678"

logger:
    level: INFO
    #level: DEBUG
    #level: VERY_VERBOSE
    #level: VERBOSE
    baud_rate: 0  
      
api:
  reboot_timeout: 0s
  encryption:
    # don't forget to replace the key
    key: "aF1rfFM9PLzYN0/+NoC7i80dnznZzGvQefPp/fIkO9I="

ota:
    # also change this password
  password: "bfd3c8c8c80be792da5e0f7d287648d5" 

    # you can remove this to conserve space
web_server:
  port: 80



